"""add procurement metadata and price catalogs

Revision ID: 4d1734fe9136
Revises: 30be1bfc7ce9
Create Date: 2026-04-28 20:30:15.497756
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '4d1734fe9136'
down_revision: Union[str, Sequence[str], None] = '30be1bfc7ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_price_catalogs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_record_id', sa.BigInteger(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('procurement_level', sa.Text(), nullable=True),
    sa.Column('procurement_scope', sa.Text(), nullable=True),
    sa.Column('procurement_type', sa.Text(), nullable=True),
    sa.Column('alliance_name', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('procurement_unit', sa.Text(), nullable=True),
    sa.Column('applicant_enterprise_id', sa.BigInteger(), nullable=True),
    sa.Column('manufacturer_id', sa.BigInteger(), nullable=True),
    sa.Column('registration_no', sa.Text(), nullable=True),
    sa.Column('component_name', sa.Text(), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('medical_insurance_code', sa.Text(), nullable=True),
    sa.Column('linked_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_unit', sa.Text(), nullable=True),
    sa.Column('procurement_volume', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('planned_volume', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_volume', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('agreed_volume', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reported_volume', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume_unit', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('execution_start_date', sa.Date(), nullable=True),
    sa.Column('execution_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_enterprise_id'], ['enterprises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['enterprises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['procurement_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bid_results', sa.Column('procurement_unit', sa.Text(), nullable=True))
    op.add_column('bid_results', sa.Column('project_name', sa.Text(), nullable=True))
    op.add_column('bid_results', sa.Column('procurement_level', sa.Text(), nullable=True))
    op.add_column('bid_results', sa.Column('procurement_scope', sa.Text(), nullable=True))
    op.add_column('bid_results', sa.Column('procurement_type', sa.Text(), nullable=True))
    op.add_column('bid_results', sa.Column('alliance_name', sa.Text(), nullable=True))
    op.add_column('bid_results', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('bid_results', sa.Column('procurement_volume', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('bid_results', sa.Column('agreed_volume', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('bid_results', sa.Column('reported_volume', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('procurement_projects', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('procurement_projects', sa.Column('procurement_level', sa.Text(), nullable=True))
    op.add_column('procurement_projects', sa.Column('procurement_scope', sa.Text(), nullable=True))
    op.add_column('procurement_projects', sa.Column('procurement_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_projects', 'procurement_type')
    op.drop_column('procurement_projects', 'procurement_scope')
    op.drop_column('procurement_projects', 'procurement_level')
    op.drop_column('procurement_projects', 'city')
    op.drop_column('bid_results', 'reported_volume')
    op.drop_column('bid_results', 'agreed_volume')
    op.drop_column('bid_results', 'procurement_volume')
    op.drop_column('bid_results', 'city')
    op.drop_column('bid_results', 'alliance_name')
    op.drop_column('bid_results', 'procurement_type')
    op.drop_column('bid_results', 'procurement_scope')
    op.drop_column('bid_results', 'procurement_level')
    op.drop_column('bid_results', 'project_name')
    op.drop_column('bid_results', 'procurement_unit')
    op.drop_table('device_price_catalogs')
    # ### end Alembic commands ###
